# {{ site.mysweetvariable }}

title: AgentC
email: Inquiry@agentc.io
description: AgentC's website
baseurl: ""
url: "https://www.agentc.io"
# Build settings
markdown: kramdown
exclude: [params.json, .DS_Store, LICENSE, README.md, feed.xml]
